### ISSUE TITLE
NSolid v2

### ISSUE THREAD

**Issue by johanneswuerbach** [nodesource/docker-nsolid#11]
While it looks like there are nsolid v2 images https://github.com/nodesource/nsolid-kubernetes/blob/dee7c20b917395e8975f055130e8a1fc3f93f9d5/sample-app/Dockerfile#L1, it seems this repository doesn't include the code used to create them.

Is there a new repository or was this just missed?

**Comment by JoeDoyle23** [comment]
It looks like this was just missed. We're working on getting them all added.

**Comment by JoeDoyle23** [comment]
We have just merged in the latest changes to the build process (#12), including the addition of the source Dockerfiles.
